version: "3.8"
services:
  lisa2-collector:
    container_name: "lisa2-collector"
    image: "lisa2-collector:latest"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - lisa2-collector
    volumes:
        - .:/code
    ports:
      - 5000:5000
