version: "3.8"
services:
  lisa2-collector:
    container_name: "mammoth-collector"
    image: "leibniz21c/mammoth-collector:1.0.0"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
      labels:
        - mammoth-collector
    volumes:
        - .:/code
    ports:
      - 20000:5000
